# Generated by Django 6.0.1 on 2026-02-03 10:24

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messanger', 'Messanger')], max_length=20)),
                ('access_token', django_cryptography.fields.encrypt(models.TextField())),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('system_prompt', models.TextField()),
                ('greeting_message', models.TextField(blank=True, null=True)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=200)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentsAi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
