# Generated by Django 6.0.1 on 2026-02-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='page_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
