# Generated by Django 6.0.1 on 2026-02-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0002_agentai_page_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentai',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
