# Generated by Django 6.0.1 on 2026-02-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0003_rename_create_at_agentai_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='ai_agent_type',
            field=models.CharField(choices=[('business', 'Business (Sales/Orders)'), ('creator', 'Content Creator (Audience)'), ('personal', 'Personal Assistant')], default='business', max_length=20),
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiAgent.agentai')),
            ],
            options={
                'unique_together': {('ai_agent', 'sender_id')},
            },
        ),
    ]
