# Generated by Django 6.0.1 on 2026-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0004_agentai_ai_agent_type_usermemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='custom_keywords',
            field=models.TextField(default='দাম, স্টক, ঠিকানা, price, info', help_text='কমা দিয়ে কি-ওয়ার্ডগুলো লিখুন'),
        ),
    ]
