# Generated by Django 6.0.1 on 2026-02-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0005_agentai_custom_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiAgent.agentai')),
            ],
        ),
    ]
