# Generated by Django 6.0.1 on 2026-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0006_missingrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentai',
            name='ai_agent_type',
            field=models.CharField(choices=[('business', 'Business / Commercial'), ('support', 'Customer Support & Service'), ('creator', 'Content Creator / Social Media'), ('personal', 'Personal Life & Productivity'), ('education', 'Education & Training'), ('other', 'Other / Custom')], default='business', help_text='এই AI এজেন্টটি মূলত কোন কাজের জন্য ব্যবহার করা হবে?', max_length=20),
        ),
    ]
