# Generated by Django 6.0.1 on 2026-02-09 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0007_alter_agentai_ai_agent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(default='messenger', max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('request_type', models.CharField(default='chat', max_length=50)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ai_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='aiAgent.agentai')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Usage Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'platform'], name='aiAgent_tok_created_69dd16_idx'), models.Index(fields=['ai_agent', 'created_at'], name='aiAgent_tok_ai_agen_47f927_idx')],
            },
        ),
    ]
