# Generated by Django 6.0.1 on 2026-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0008_tokenusagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentai',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('facebook_comment', 'Facebook Comment')], max_length=20),
        ),
    ]
