# Generated by Django 6.0.1 on 2026-03-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0010_dashboardailog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. GPT-4o Mini, Gemini Pro', max_length=100)),
                ('model_id', models.CharField(help_text='e.g. gpt-4o-mini, gemini-2.0-flash', max_length=100)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('grok', 'xAI Grok'), ('openrouter', 'OpenRouter')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentai',
            name='selected_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiAgent.aiprovidermodel'),
        ),
    ]
