# Generated by Django 6.0.1 on 2026-03-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0011_aiprovidermodel_agentai_selected_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='memory_extraction_model',
            field=models.ForeignKey(blank=True, help_text='এজেন্ট মেমোরি এক্সট্রাকশনের জন্য কোন মডেল ব্যবহার হবে? (শুধুমাত্র অ্যাডমিন)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_memory_extraction', to='aiAgent.aiprovidermodel'),
        ),
    ]
