# Generated by Django 6.0.1 on 2026-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0012_agentai_memory_extraction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='is_special_agent',
            field=models.BooleanField(default=False, help_text='বিশেষ এজেন্টদের ডাটা দীর্ঘক্ষণ (১ বছর) ক্যাশে থাকবে'),
        ),
    ]
