# Generated by Django 6.0.1 on 2026-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0013_agentai_is_special_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='special_agent_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text="Status of the user's request for Special Agent features.", max_length=20),
        ),
    ]
