# Generated by Django 6.0.1 on 2026-03-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0014_agentai_special_agent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('location', 'Location / Geography'), ('skip', 'Skip Keyword (Greetings/Filler)'), ('target', 'Target Keyword (High Priority)'), ('intent', 'User Intent (Order/Price)'), ('urgency', 'Urgency / Sentiment (Problem/Slow)')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Smart Keyword',
                'verbose_name_plural': 'Smart Keywords',
            },
        ),
    ]
