# Generated by Django 6.0.1 on 2026-03-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0015_smartkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartkeyword',
            name='category',
            field=models.CharField(choices=[('location', 'Location / Geography'), ('skip', 'Skip Keyword (Greetings/Filler)'), ('target', 'Target Keyword (High Priority)'), ('intent', 'User Intent (Order/Price)'), ('urgency', 'Urgency'), ('number', 'Numeric Keyword')], db_index=True, max_length=20),
        ),
    ]
