# Generated by Django 6.0.1 on 2026-03-16 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0016_alter_smartkeyword_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smartkeyword',
            name='category',
            field=models.CharField(choices=[('location', 'Location / Geography'), ('skip', 'Skip Keyword (Greetings/Filler)'), ('history_skip', 'History Skip (No History in AI)'), ('embedding_skip', 'Embedding Skip (No RAG Search)'), ('target', 'Target Keyword (High Priority)'), ('intent', 'User Intent (Order/Price)'), ('urgency', 'Urgency'), ('number', 'Numeric Keyword')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermemory',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
