# Generated by Django 6.0.1 on 2026-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0017_usermemory_created_at_alter_smartkeyword_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartkeyword',
            name='text',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='smartkeyword',
            unique_together={('text', 'category')},
        ),
        migrations.AddIndex(
            model_name='smartkeyword',
            index=models.Index(fields=['category', 'text'], name='aiAgent_sma_categor_78975c_idx'),
        ),
    ]
