# Generated by Django 6.0.1 on 2026-03-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0018_alter_smartkeyword_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardailog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
