# Generated by hand (Antigravity AI) on 2026-03-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0028_remove_agentai_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='widget_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agentai',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('facebook_comment', 'Facebook Comment'), ('web_widget', 'Web Chat Widget')], max_length=20),
        ),
        migrations.CreateModel(
            name='WidgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4f46e5', max_length=7)),
                ('bubble_icon', models.CharField(default='chat', max_length=50)),
                ('widget_position', models.CharField(default='bottom-right', max_length=20)),
                ('header_title', models.CharField(default='Chat with AI', max_length=100)),
                ('header_subtitle', models.CharField(default='Online | Powered by Smart Agent', max_length=100)),
                ('placeholder_text', models.CharField(default='Type a message...', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('allowed_domains', models.TextField(blank=True, help_text='Comma separated domains (e.g. example.com). Leave blank for all.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_settings', to='aiAgent.agentai')),
            ],
        ),
    ]
