# Generated by hand (Antigravity AI) on 2026-03-20

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0029_web_widget_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentai',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='agentai',
            name='page_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
