# Generated by hand (Antigravity AI) on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0030_relax_agentai_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='bubble_icon_url',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Custom bubble icon URL. Leave blank to use the default newsmartagent logo.',
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name='widgetsettings',
            name='bubble_icon',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
