# Generated by hand (Antigravity AI) on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0031_widgetsettings_bubble_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='bubble_size',
            field=models.IntegerField(
                default=60,
                help_text='Bubble size in pixels (e.g. 52, 60, 72).',
            ),
        ),
        migrations.AlterField(
            model_name='widgetsettings',
            name='widget_position',
            field=models.CharField(
                default='bottom-right',
                help_text='Corner position: bottom-right, bottom-left, top-right, top-left',
                max_length=20,
            ),
        ),
    ]
