# Generated by Django 6.0.1 on 2026-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0032_widgetsettings_bubble_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='bubble_roundness',
            field=models.IntegerField(default=28, help_text='Bubble corner roundness in percentage (0-100).'),
        ),
        migrations.AddField(
            model_name='widgetsettings',
            name='show_bubble_background',
            field=models.BooleanField(default=True, help_text='Whether to show the primary color background for the bubble.'),
        ),
    ]
