# Generated by Django 6.0.1 on 2026-03-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0033_widgetsettings_bubble_roundness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='messenger_link',
            field=models.CharField(blank=True, help_text='Facebook Messenger link (e.g. m.me/yourpage)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widgetsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20, null=True),
        ),
    ]
