# Generated by Django 6.0.1 on 2026-03-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0035_apiconfig_websitevisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_human_needed',
            field=models.BooleanField(default=False, help_text='Set to True if the user needs human assistance.'),
        ),
    ]
