# Generated by Django 6.0.1 on 2026-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0036_contact_is_human_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentai',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('facebook_comment', 'Facebook Comment'), ('instagram', 'Instagram'), ('web_widget', 'Web Chat Widget')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('web_widget', 'Web Chat Widget'), ('facebook_comment', 'Facebook Comment')], max_length=20),
        ),
    ]
