# Generated by Django 6.0.1 on 2026-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0037_alter_agentai_platform_alter_contact_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentai',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('facebook_comment', 'Facebook Comment'), ('instagram', 'Instagram'), ('web_widget', 'Web Chat Widget'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
