# Generated by Django 6.0.1 on 2026-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0040_telegrambot'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='enable_ai_control',
            field=models.BooleanField(default=False, help_text='Show AI Off/On toggle button in the widget'),
        ),
        migrations.AddField(
            model_name='widgetsettings',
            name='enable_human_control',
            field=models.BooleanField(default=False, help_text='Show Human Help / Resolve button in the widget'),
        ),
    ]
