# Generated by Django 6.0.1 on 2026-03-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0041_add_chat_controls_to_widget_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='menu_ai_icon_bg_color',
            field=models.CharField(blank=True, help_text='Background color for AI icon in FAB menu (leave blank for transparent)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='widgetsettings',
            name='menu_ai_icon_size',
            field=models.IntegerField(default=44, help_text='AI Icon size in the 3-icon menu'),
        ),
        migrations.AlterField(
            model_name='widgetsettings',
            name='enable_ai_control',
            field=models.BooleanField(default=True, help_text='Show AI Off/On toggle button in the widget'),
        ),
        migrations.AlterField(
            model_name='widgetsettings',
            name='enable_human_control',
            field=models.BooleanField(default=True, help_text='Show Human Help / Resolve button in the widget'),
        ),
    ]
