# Generated by Django 6.0.1 on 2026-03-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0042_add_menu_icon_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetsettings',
            name='menu_ai_icon_roundness',
            field=models.IntegerField(default=50, help_text='AI Icon corner roundness in percentage (0-100)'),
        ),
    ]
