# Generated by Django 6.0.1 on 2026-03-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0044_alter_agentai_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentai',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('facebook_comment', 'Facebook Comment'), ('instagram', 'Instagram'), ('web_widget', 'Web Chat Widget'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('gbp', 'Google Business Profile')], max_length=20),
        ),
    ]
