# Generated by Django 6.0.1 on 2026-03-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0045_alter_agentai_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='contact_profiles/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile_picture_hash',
            field=models.CharField(blank=True, help_text='MD5 hash to prevent duplicate MinIO uploads', max_length=64, null=True),
        ),
    ]
