# Generated by Django 6.0.1 on 2026-03-28 16:27

import django.db.models.deletion
import minio_management.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0046_contact_profile_picture_contact_profile_picture_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('web_widget', 'Web Chat Widget'), ('facebook_comment', 'Facebook Comment'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=minio_management.storages.ContactProfileStorage(), upload_to='contact_profiles/'),
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('audience_count', models.IntegerField(default=0)),
                ('filter_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='aiAgent.agentai')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
