# Generated by Django 6.0.1 on 2026-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0047_alter_contact_platform_alter_contact_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='schedule_delay_ms',
            field=models.PositiveIntegerField(default=0, help_text='প্রতি মেসেজের মাঝে বিলম্ব (মিলিসেকেন্ড)'),
        ),
        migrations.AddField(
            model_name='agentai',
            name='schedule_max_batch',
            field=models.PositiveIntegerField(default=500, help_text='একটি schedule রান-এ সর্বোচ্চ কতজনকে পাঠানো হবে'),
        ),
    ]
