# Generated by Django 6.0.1 on 2026-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0048_agentai_schedule_delay_ms_agentai_schedule_max_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentai',
            name='schedule_delay_ms',
        ),
        migrations.AddField(
            model_name='agentai',
            name='schedule_delay_seconds',
            field=models.PositiveIntegerField(default=0, help_text='প্রতি মেসেজের মাঝে বিলম্ব (সেকেন্ড)'),
        ),
    ]
