# Generated by Django 6.0.1 on 2026-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0049_remove_agentai_schedule_delay_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentai',
            name='schedule_delay_seconds',
        ),
        migrations.AddField(
            model_name='agentai',
            name='schedule_delay_ms',
            field=models.PositiveIntegerField(default=0, help_text='প্রতি মেসেজের মাঝে বিলম্ব (মিলিসেকেন্ড)'),
        ),
    ]
