# Generated by Django 6.0.1 on 2026-03-29
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_schedule_quota_fields'),
        ('aiAgent', '0050_remove_agentai_schedule_delay_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='consumed_quota',
            field=models.PositiveIntegerField(default=1, help_text='How many schedule slots this entry consumed'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='consumed_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_schedules', to='users.subscription'),
        ),
    ]
