# Generated by Django (manual creation)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0051_scheduledmessage_consumed_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentai',
            name='prompt_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens consumed by the system prompt'),
        ),
    ]
