# Generated by Django 6.0.1 on 2026-03-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0052_agentai_prompt_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTokenReport',
            fields=[
            ],
            options={
                'verbose_name': 'Prompt Token Analytics',
                'verbose_name_plural': 'Prompt Token Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aiAgent.agentai',),
        ),
    ]
