# Generated by Django 6.0.1 on 2026-05-28 09:36

import minio_management.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0054_add_widget_cancel_drag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='heard_voice_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=minio_management.storages.ContactProfileStorage(), upload_to='contact_profiles/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile_photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
