# Generated by Django 6.0.1 on 2026-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0056_add_agentai_image_caption_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitevisitor',
            name='sender_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
