tunnel: e4b9a4e5-29c2-4681-bbc6-c2d02321784b
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: dev.newsmartagent.com
    service: http://nginx:80
  - hostname: dev-api.newsmartagent.com
    service: http://nginx:80
  - hostname: dev-n8n.newsmartagent.com
    service: http://n8n:5678
  - hostname: dev-minio.newsmartagent.com
    service: http://nginx:80
  - hostname: dev-s3.newsmartagent.com
    service: http://nginx:80
  - service: http_status:404

edge-ip-version: auto
protocol: http2
