# Generated by Django 6.0.1 on 2026-05-26 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0046_trusteddevice_is_trusted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoBookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(help_text='Consignment ID returned by Pathao', max_length=100, unique=True)),
                ('merchant_order_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathao_bookings', to='users.customerorder')),
            ],
        ),
        migrations.CreateModel(
            name='PathaoCourierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('username', models.CharField(help_text='Pathao Merchant Registered Email/Username', max_length=255)),
                ('password', models.CharField(help_text='Pathao Merchant Password', max_length=255)),
                ('store_id', models.CharField(blank=True, help_text='Default Store ID to book orders', max_length=100, null=True)),
                ('is_sandbox', models.BooleanField(default=True, help_text='Check to use Pathao Sandbox environment')),
                ('is_active', models.BooleanField(default=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathao_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
