# Generated by Django 6.0.1 on 2026-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_pathaocity_pathaozone_pathaoarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathaoZonePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100)),
                ('city_id', models.IntegerField()),
                ('zone_id', models.IntegerField()),
                ('weight', models.FloatField(default=0.5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'city_id', 'zone_id', 'weight'], name='courier_pat_store_i_4ce294_idx')],
                'unique_together': {('store_id', 'city_id', 'zone_id', 'weight')},
            },
        ),
    ]
