# Generated by Django 6.0.1 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_add_courier_config_name_and_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='steadfastareaprice',
            new_name='courier_ste_city_id_5ef919_idx',
            old_name='courier_ste_city_id_abc123_idx',
        ),
        migrations.AlterField(
            model_name='steadfastcourierconfig',
            name='is_sandbox',
            field=models.BooleanField(default=True, help_text='Check to use Steadfast Sandbox environment'),
        ),
    ]
