
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: newsmartagent-db
    #!!!! must be named volume in production

    volumes:
    # named volume
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c shared_buffers=4GB -c effective_cache_size=10GB -c work_mem=64MB -c maintenance_work_mem=1GB
    restart: always
    networks:
      - smart-network
      
  redis:
    image: redis/redis-stack-server:latest
    container_name: newsmartagent-redis
    restart: always
    networks:
      smart-network:
        aliases:
          - newsmartagent-redis
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --loadmodule /opt/redis-stack/lib/redisearch.so
      --loadmodule /opt/redis-stack/lib/rejson.so
      --maxmemory 6gb
      --maxmemory-policy allkeys-lru
      --protected-mode no
      --appendonly yes
      --appendfsync everysec
      --save 60 1000

  backend:
    build: ./jwtauth
    container_name: newsmartagent-django
    command: gunicorn jwtauth.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 5 --threads 4 --timeout 120
    volumes:
      - ./jwtauth:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - /home/ubuntu/configs/service_account.json:/app/gdrive_key.json:ro
    
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@newsmartagent-db:5432/${POSTGRES_DB}     
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - FB_APP_ID=890689390590685
      - FB_APP_SECRET=7c0693dacfc6211613d16437be2192b8
      - FB_REDIRECT_URI=https://newsmartagent.com/api/facebook/callback/
      - GOOGLE_DRIVE_LOG_FOLDER_ID=${GOOGLE_DRIVE_LOG_FOLDER_ID}
      - GOOGLE_DRIVE_LOG_SUBFOLDER=${GOOGLE_DRIVE_LOG_SUBFOLDER}
      - GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE=/app/gdrive_key.json
    depends_on:
      - db
      - redis
    deploy:
      update_config:
        order: start-first # জিরো ডাউনটাইম নিশ্চিত করবে
      resources:
        limits:
          memory: 4G
    networks:
      - smart-network


  frontend:
    build: ./nextjs
    container_name: newsmartagent-nextjs
    environment:
      - NEXT_PUBLIC_BASE_URL=https://newsmartagent.com
      - NEXT_PUBLIC_API_URL=https://newsmartagent.com/api
    restart: always
    depends_on:
      - backend
    deploy:
      update_config:
        order: start-first
      resources:
        limits:
          memory: 4G
    
    networks:
      - smart-network

  nginx:
    build: ./nginx
    container_name: newsmartagent-nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
       - backend
       - frontend
    deploy:
      update_config:
        order: start-first
    restart: always
    networks:
      - smart-network


  celery_worker:
    build: ./jwtauth
    container_name: newsmartagent-celery-worker
    command: celery -A jwtauth worker -Q chat_queue -c 8 --prefetch-multiplier 1 --max-tasks-per-child 1000 --loglevel=info
    volumes:
      - ./jwtauth:/app
      - /home/ubuntu/configs/service_account.json:/app/gdrive_key.json:ro
    env_file:
      - .env
    
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@newsmartagent-db:5432/${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_DRIVE_LOG_FOLDER_ID=${GOOGLE_DRIVE_LOG_FOLDER_ID}
      - GOOGLE_DRIVE_LOG_SUBFOLDER=${GOOGLE_DRIVE_LOG_SUBFOLDER}
      - GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE=/app/gdrive_key.json

    depends_on:
      - db
      - redis
    networks:
      - smart-network
    restart: always

  celery_beat:
    build: ./jwtauth
    container_name: newsmartagent-celery-beat
    command: celery -A jwtauth beat -l info
    volumes:
      - ./jwtauth:/app
      - /home/ubuntu/configs/service_account.json:/app/gdrive_key.json:ro
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@newsmartagent-db:5432/${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_DRIVE_LOG_FOLDER_ID=${GOOGLE_DRIVE_LOG_FOLDER_ID}
      - GOOGLE_DRIVE_LOG_SUBFOLDER=${GOOGLE_DRIVE_LOG_SUBFOLDER}
      - GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE=/app/gdrive_key.json
    depends_on:
      - db
      - redis
    networks:
      - smart-network

  n8n:
    image: n8nio/n8n:latest
    container_name: newsmartagent-n8n
    environment:
      N8N_HOST: n8n.newsmartagent.com
      N8N_URL: https://n8n.newsmartagent.com
      WEBHOOK_URL: https://n8n.newsmartagent.com
      N8N_TRUST_PROXY: "true"
      EXPLICIT_TRUST_PROXY: "true" # এটি মাস্ট যোগ করুন
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false" # কনফিগ ফাইল পারমিশন ইস্যু এড়াতে
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_PROTOCOL: https
      GENERIC_TIMEZONE: Asia/Dhaka
      NODE_OPTIONS: --max-old-space-size=2048
      # 🔥 Add these
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: newsmartagent-db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - backend
      - redis
      - db
    deploy:
      update_config:
        order: start-first
    restart: always 
    networks:
      - smart-network
  
  flower:
    image: mher/flower
    container_name: newsmartagent-flower
    command: celery --broker=${REDIS_URL} flower --basic_auth=${FLOWER_BASIC_AUTH}
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - smart-network


  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: newsmartagent-cloudflare-tunnel
    user: root
    restart: always
    deploy:
      update_config:
        order: start-first
    dns:
      - 1.1.1.1 
    networks:
      - smart-network
    volumes:
      - /home/ubuntu/cloudflare-config:/etc/cloudflared:ro
    command: tunnel --config /etc/cloudflared/config.yml run
    depends_on:
      - nginx


volumes:
  postgres_data:
    external: true
    name: production_pg_data
  redis_data:
    name: production_redis_data
  static_volume:
    name: newsmartagent-static
  media_volume:
    name: newsmartagent-media
  n8n_data:
    name: production_n8n_data
  

networks:
  smart-network:
    name: smart-network 
    driver: bridge