# Generated by Django 6.0.1 on 2026-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_reportcomment_reportlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='category',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feedback', 'Feedback'), ('Feature', 'Feature'), ('Review', 'Review'), ('Roadmap', 'Roadmap')], default='Feedback', max_length=20),
        ),
    ]
