# Generated by Django 6.0.1 on 2026-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communityreport_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
