# Generated by Django 6.0.1 on 2026-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_reportcomment_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Planned', 'Planned'), ('In Review', 'In Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Fixed', 'Fixed'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Open', max_length=12),
        ),
    ]
