# Generated by Django 6.0.1 on 2026-02-05 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untiteled Sheet', max_length=255)),
                ('rows', models.PositiveIntegerField(default=20)),
                ('cols', models.PositiveIntegerField(default=20)),
                ('data', models.JSONField(default=dict, help_text="Stores cell values as {'0-1': 'Hello'}")),
                ('colors', models.JSONField(default=dict, help_text="Stores cell colors as {'0-1': '#ffffff'}")),
                ('styles', models.JSONField(default=dict, help_text="Stores cell styles as {'0-1': {'fontWeight': 'bold'}}")),
                ('is_dark_mode', models.BooleanField(default=False)),
                ('zoom_level', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
