# Generated by Django 6.0.1 on 2026-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='colors',
            field=models.JSONField(blank=True, default=dict, help_text="Stores cell colors as {'0-1': '#ffffff'}", null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text="Stores cell values as {'0-1': 'Hello'}", null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='styles',
            field=models.JSONField(blank=True, default=dict, help_text="Stores cell styles as {'0-1': {'fontWeight': 'bold'}}", null=True),
        ),
    ]
