# Generated by Django (manual creation)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0003_spreadsheet_agent_spreadsheet_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='tokens_count',
            field=models.IntegerField(default=0, help_text='Total tokens consumed by the spreadsheet data'),
        ),
    ]
