# Generated by Django 6.0.1 on 2026-07-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0005_auto_image_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='image_search_log',
            field=models.TextField(blank=True, default='', help_text='Logs of the latest auto image search execution'),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='image_search_source_url',
            field=models.TextField(blank=True, default='', help_text='Target website URL to restrict image search'),
        ),
    ]
