# Generated by Django 6.0.1 on 2026-03-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0003_document_documentknowledge_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='full_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentknowledge',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
