# Generated by Django 6.0.1 on 2026-05-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0002_add_image_fields'),
        ('embedding', '0006_document_tokens_count'),
    ]

    operations = [
    ]
