# Generated by Django 6.0.1 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0007_merge_20260601_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheetknowledge',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
