# Generated by Django 6.0.1 on 2026-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0008_alter_spreadsheetknowledge_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheetknowledge',
            name='image_caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
