# Generated by Django 6.0.1 on 2026-06-02 15:38

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0009_spreadsheetknowledge_image_caption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(db_index=True, max_length=50)),
                ('image_url', models.TextField()),
                ('image_filename', models.CharField(blank=True, default='', max_length=255)),
                ('image_caption', models.TextField(blank=True, default='')),
                ('image_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto_search', 'Auto Search'), ('playwright', 'Playwright')], default='manual', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for row thumbnail')),
                ('position', models.IntegerField(default=0, help_text='Order index for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['image_embedding'], m=16, name='row_image_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'unique_together': {('user', 'row_id', 'image_url')},
            },
        ),
    ]
