# Generated by Django 6.0.1 on 2026-06-04 15:41

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0010_rowimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rowimage',
            name='caption_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='rowimage',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['caption_embedding'], m=16, name='row_image_caption_emb_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
