# Generated by Django 6.0.1 on 2026-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0011_rowimage_caption_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowimage',
            name='source_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
