# Generated by Django 6.0.1 on 2026-08-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0012_rowimage_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RowSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_id', models.CharField(db_index=True, max_length=50)),
                ('target_row_id', models.CharField(db_index=True, max_length=50)),
                ('distance', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_similarities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source_row_id', 'target_row_id')},
            },
        ),
    ]
