# Generated by Django 6.0.1 on 2026-03-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0019_dashboardailog_message_id'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_ai_model', models.ForeignKey(blank=True, help_text='Select the AI model that will be used globally for the Dashboard Assistant (New Smart Agent).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiAgent.aiprovidermodel')),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
