# Generated by Django 6.0.1 on 2026-03-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0034_widgetsettings_messenger_link_and_more'),
        ('settings', '0004_agentaisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaisettings',
            name='shared_cache_agent',
            field=models.ForeignKey(blank=True, help_text='অন্য কোনো এজেন্টের ক্যাশ শেয়ার করতে চাইলে সেই এজেন্টটি সিলেক্ট করুন।', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_by_settings', to='aiAgent.agentai'),
        ),
    ]
