# Generated by Django 6.0.1 on 2026-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0034_widgetsettings_messenger_link_and_more'),
        ('settings', '0005_agentaisettings_shared_cache_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentaisettings',
            name='shared_cache_agent',
        ),
        migrations.AddField(
            model_name='agentaisettings',
            name='shared_cache_agents',
            field=models.ManyToManyField(blank=True, help_text='অন্য কোনো এজেন্টদের ক্যাশ শেয়ার করতে চাইলে সেই এজেন্টগুলো সিলেক্ট করুন।', related_name='shared_by_settings', to='aiAgent.agentai'),
        ),
    ]
