# Generated by Django 6.0.1 on 2026-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_agentaisettings_shared_cache_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='youtube_check_interval',
            field=models.PositiveIntegerField(default=1, help_text='How often to check for new YouTube comments (in minutes).'),
        ),
    ]
