# Generated by Django 6.0.1 on 2026-07-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_add_globalsettings_image_caption_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaisettings',
            name='redis_cache_enabled',
            field=models.BooleanField(default=False, help_text='রেডিস মেসেজ ক্যাশিং চালু করতে চান কি না?'),
        ),
    ]
