# Generated by Django 6.0.1 on 2026-01-31 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_offer_payment_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='profile',
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.subscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='shorthand_choices',
            field=models.CharField(blank=True, choices=[('k', 'K'), ('m', 'M'), ('b', 'B'), ('unlimited', 'Unlimited'), ('word', 'Word')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], max_length=20),
        ),
    ]
