# Generated by Django 6.0.1 on 2026-02-01 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_payment_profile_payment_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.AddField(
            model_name='payment',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_payments', to='users.offer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_payments', to='users.profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='word',
            field=models.PositiveIntegerField(),
        ),
    ]
