# Generated by Django 6.0.1 on 2026-02-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payment_currency_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='word',
            new_name='tokens',
        ),
        migrations.AlterField(
            model_name='offer',
            name='shorthand_choices',
            field=models.CharField(blank=True, choices=[('k', 'K'), ('m', 'M'), ('b', 'B'), ('unlimited', 'Unlimited')], max_length=10, null=True),
        ),
    ]
