# Generated by Django 6.0.1 on 2026-02-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_word_offer_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='BDT', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='allowed_platforms',
            field=models.ManyToManyField(related_name='offers', to='users.platform'),
        ),
    ]
