# Generated by Django 6.0.1 on 2026-02-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_platform_alter_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='word_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
