# Generated by Django 6.0.1 on 2026-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_word_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='shorthand_choices',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
