# Generated by Django 6.0.1 on 2026-02-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customerorder_orderform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
