# Generated by Django 6.0.1 on 2026-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customerorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='upazila',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
