# Generated by Django 6.0.1 on 2026-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customerorder_district_customerorder_upazila'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acount_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='commission_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
