# Generated by Django 6.0.1 on 2026-02-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_acount_balance_profile_commission_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('balance', 'Add Balance')], default='subscription', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_payments', to='users.offer'),
        ),
    ]
