# Generated by Django 6.0.1 on 2026-02-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('created_by_agent', 'Created By Agent')], default='all', max_length=20),
        ),
    ]
