# Generated by Django 6.0.1 on 2026-02-19 05:07

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_nsatransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter number with country code (e.g. +88017...)', max_length=20, validators=[users.validators.validate_international_phone], verbose_name='Phone Number'),
        ),
    ]
