# Generated by Django 6.0.1 on 2026-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiAgent', '0011_aiprovidermodel_agentai_selected_model'),
        ('users', '0023_user_country_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='allowed_models',
            field=models.ManyToManyField(blank=True, related_name='offers', to='aiAgent.aiprovidermodel'),
        ),
    ]
