# Generated by Django 6.0.1 on 2026-03-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profile_otp_code_profile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='remaining_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
