# Generated by Django 6.0.1 on 2026-03-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_facebookpage_withdrawmethod_cashoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmethod',
            name='account_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('agent', 'Agent'), ('merchant', 'Merchant')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawmethod',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawmethod',
            name='card_type',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawmethod',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Bank Card (Debit/Credit)')], max_length=20),
        ),
    ]
