# Generated by Manuel Agentic Flow on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_withdrawmethod_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
