# Generated by Django 6.0.1 on 2026-03-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_customerorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_secret',
        ),
    ]
