# Generated by Django 6.0.1 on 2026-03-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_customerorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
