# Generated by Django 6.0.1 on 2026-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_facebookpage_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
