# Generated by Django 6.0.1 on 2026-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_youtubechannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='last_comment_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
