# Generated by Django 6.0.1 on 2026-03-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_youtubechannel_last_comment_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCommentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('comment_id', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('ai_reply', models.TextField()),
                ('status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.youtubechannel')),
            ],
        ),
    ]
