# Generated by Django 6.0.1 on 2026-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_youtubecommentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='custom_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
