# Generated by Django 6.0.1 on 2026-03-29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_tiktokaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='schedule_messages',
            field=models.PositiveIntegerField(default=0, help_text='এই অফারে মোট কতটি শিডিউল মেসেজ পাঠাতে পারবে'),
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule_balance',
            field=models.PositiveBigIntegerField(default=0, help_text='Remaining schedule message slots across active subscriptions'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='remaining_schedule_messages',
            field=models.PositiveBigIntegerField(default=0, help_text='Remaining schedule message slots for this subscription'),
        ),
    ]
