# Generated by Django 6.0.1 on 2026-03-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_schedule_quota_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='schedule_messages',
            field=models.PositiveIntegerField(default=0, help_text='এই অফারে মোট কয়জন কন্টাক্টকে শিডিউল মেসেজ পাঠানো যাবে (মোট অডিয়েন্স)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='schedule_balance',
            field=models.PositiveBigIntegerField(default=0, help_text='Remaining schedule recipients across active subscriptions'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='remaining_schedule_messages',
            field=models.PositiveBigIntegerField(default=0, help_text='এই সাবস্ক্রিপশনে বাকি থাকা শিডিউল অডিয়েন্স সংখ্যা'),
        ),
    ]
