# Generated by Django 6.0.1 on 2026-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_profile_recovery_email_profile_recovery_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='trust_device',
            field=models.BooleanField(default=False),
        ),
    ]
