# Generated by Django 6.0.1 on 2026-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_loginsession_trust_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
