# Generated by Django 6.0.1 on 2026-05-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_trusteddevice_is_trusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='area_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='city_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='item_weight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='special_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='zone_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
