# Generated by Django 6.0.1 on 2026-05-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_customerorder_area_id_customerorder_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='source_contact_id',
            field=models.CharField(blank=True, help_text='Platform-specific contact ID (sender_id)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='source_platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('web', 'Web Form'), ('facebook_comment', 'Facebook Comment'), ('other', 'Other')], db_index=True, default='web', max_length=20),
        ),
    ]
