# Generated by Django 6.0.1 on 2026-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_customerorder_invoice_task_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text="List of items: [{'name': '...', 'quantity': 1, 'price': 100}]", null=True),
        ),
    ]
