# Generated by Django 6.0.1 on 2026-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_profile_business_email_profile_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image_support',
            field=models.BooleanField(default=False, help_text='ইমেজ সাপোর্ট সচল করতে এটি সিলেক্ট করুন'),
        ),
    ]
