# Generated by Django 6.0.1 on 2026-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_conversation_alter_message_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'AI'), ('system', 'System')], max_length=20),
        ),
    ]
