# Generated by Django 6.0.1 on 2026-03-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_platform_message_platform_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_agentAi_ad1fb4_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_agentAi_e20d1f_idx',
            old_name='chat_conver_agentAi_3c063a_idx',
        ),
    ]
