import React from 'react';

const TermsOfService = () => {
  return (
    <div className="bg-[#fcfcfd] min-h-screen py-10 md:py-20 px-4 sm:px-6 lg:px-8 font-sans text-slate-800">
      <div className="max-w-4xl mx-auto bg-white shadow-sm border border-slate-100 rounded-3xl overflow-hidden">
        
        {/* Header */}
        <div className="bg-slate-900 p-8 md:p-12 text-center">
          <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-4">
            Terms of Service
          </h1>
          <p className="text-slate-400 text-sm md:text-base">
            Last Updated: March 6, 2026
          </p>
        </div>

        <div className="p-8 md:p-12 space-y-10">
          
          {/* 1. Introduction */}
          <section className="space-y-4">
            <h2 className="text-xl md:text-2xl font-bold text-slate-900 flex items-center gap-2">
              <span className="w-1.5 h-6 bg-blue-600 rounded-full"></span>
              1. Agreement to Terms
            </h2>
            <p className="leading-relaxed text-slate-600">
              By accessing or using <strong>New Smart Agent</strong> (https://newsmartagent.com/), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services.
            </p>
          </section>

          {/* 2. Description of Service */}
          <section className="space-y-4 text-slate-600">
            <h2 className="text-xl md:text-2xl font-bold text-slate-900 flex items-center gap-2">
              <span className="w-1.5 h-6 bg-blue-600 rounded-full"></span>
              2. Description of Service
            </h2>
            <p className="leading-relaxed">
              New Smart Agent provides AI-powered automation tools for Facebook Messenger and WhatsApp. Our services include automated replies, comment management, and business productivity enhancements using AI models like GPT-4o-mini.
            </p>
          </section>

          {/* 3. User Responsibilities */}
          <section className="space-y-4 bg-slate-50 p-6 rounded-2xl border border-slate-100">
            <h2 className="text-xl font-bold text-slate-900">3. User Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-2 text-slate-600 text-sm md:text-base">
              <li>You must be at least 18 years old to use this service.</li>
              <li>You are responsible for maintaining the security of your account and access tokens.</li>
              <li>You agree not to use the service for any illegal or unauthorized purpose (e.g., spamming or harassment).</li>
              <li>You must comply with Meta's (Facebook/Instagram) Community Standards and Policies while using our automation.</li>
            </ul>
          </section>

          {/* 4. Data Usage & AI Content */}
          <section className="space-y-4">
            <h2 className="text-xl md:text-2xl font-bold text-slate-900 flex items-center gap-2">
              <span className="w-1.5 h-6 bg-blue-600 rounded-full"></span>
              4. AI Content Disclaimer
            </h2>
            <p className="leading-relaxed text-slate-600">
              Our service uses Artificial Intelligence to generate responses. While we strive for accuracy, New Smart Agent is not responsible for any incorrect, offensive, or unintended content generated by the AI. Users are advised to monitor their AI agents' activities.
            </p>
          </section>

          {/* 5. Payments and Refunds */}
          <section className="space-y-4">
            <h2 className="text-xl md:text-2xl font-bold text-slate-900 flex items-center gap-2">
              <span className="w-1.5 h-6 bg-blue-600 rounded-full"></span>
              5. Payments and Subscriptions
            </h2>
            <p className="leading-relaxed text-slate-600">
              Certain features of New Smart Agent require a paid subscription. Payments are processed securely via third-party gateways (SSLCommerz). Subscription fees are non-refundable unless otherwise stated.
            </p>
          </section>

          {/* 6. Termination */}
          <section className="space-y-4">
            <h2 className="text-xl md:text-2xl font-bold text-slate-900 flex items-center gap-2">
              <span className="w-1.5 h-6 bg-blue-600 rounded-full"></span>
              6. Termination
            </h2>
            <p className="leading-relaxed text-slate-600">
              We reserve the right to terminate or suspend your account immediately, without prior notice, if you breach these Terms of Service.
            </p>
          </section>

          {/* 7. Contact Us */}
          <section className="mt-12 pt-8 border-t border-slate-100 text-center">
            <h2 className="text-lg font-bold text-slate-900 mb-2">Questions about Terms?</h2>
            <p className="text-slate-500 mb-4 text-sm">আমাদের টার্মস নিয়ে কোনো প্রশ্ন থাকলে সরাসরি আমাদের ইমেইল করুন।</p>
            <a 
              href="mailto:newsmartagentbd@gmail.com" 
              className="inline-block px-8 py-3 bg-blue-600 text-white font-bold rounded-xl hover:bg-blue-700 transition-all shadow-lg shadow-blue-200"
            >
              newsmartagentbd@gmail.com
            </a>
          </section>

        </div>

        <footer className="bg-slate-50 p-6 text-center border-t border-slate-100">
          <p className="text-slate-400 text-xs md:text-sm italic">
            &copy; {new Date().getFullYear()} New Smart Agent. Terms and conditions are subject to change without notice.
          </p>
        </footer>
      </div>
    </div>
  );
};

export default TermsOfService;