"""
Django settings for jwtauth project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i6it!d42&fu(j0*&)*53ymr5k+7osf^r__i$+@vds)a#7r-&^^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['newsmartagent.com', 'api.newsmartagent.com', 'n8n.newsmartagent.com', 'newsmartagent-django', 'newsmartagent-n8n', 'localhost','127.0.0.1', 'monitor.newsmartagent.com', 'dev.newsmartagent.com', 'dev-api.newsmartagent.com', 'dev.newsmartagent.com', 'dev-n8n.newsmartagent.com', 'backend', 'newsmartagent-baileys']
CSRF_TRUSTED_ORIGINS = ['https://newsmartagent.com', 'https://api.newsmartagent.com', 'https://n8n.newsmartagent.com', 'http://newsmartagent-django:8000', 'https://monitor.newsmartagent.com', 'https://dev.newsmartagent.com', 'https://dev-api.newsmartagent.com', 'https://dev-n8n.newsmartagent.com']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users',
    'corsheaders',
    'allauth',
    'allauth.account',
    # 'allauth.socialaccount.providers.google',
    'payments',
    'n8n',
    'webhooks',

    'chat',
    'datasheet',
    'openwa',
    'evolution',
    'django_celery_beat',
    'pgvector',
    'embedding',
    'blog',
    'django.contrib.postgres',
    'settings',
    'man_agent',
    "aiAgent.apps.AiagentConfig",
    'ckeditor',
    'log_service',
    

    'ckeditor_uploader',
]

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_BASEPATH = "https://cdn.ckeditor.com/4.22.1/full-all/"

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # "users.middleware.TokenMiddleware",

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
        # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",

]

ROOT_URLCONF = 'jwtauth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'), 
            os.path.join(BASE_DIR, 'jwtauth', 'templates'), # এটি যোগ করুন
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
 # `allauth` needs this from django

            ],
        },
    },
]

WSGI_APPLICATION = 'jwtauth.wsgi.application'
ASGI_APPLICATION = 'jwtauth.asgi.application'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("newsmartagent-redis", 6379)], # আপনার রেডিস কন্টেইনার নাম
        },
    },
}

CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'sep_timeout': 30,
}
CELERY_REDIS_RETRY_ON_TIMEOUT = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # ৫০টি কাজ শেষে ওয়ার্কার ফ্রেশ হবে
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 500 * 1024  # ৫০০ এমবি ক্রস করলে রিস্টার্ট
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 110
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get('SOCIAL_AUTH_FACEBOOK_SECRET')
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "/app/static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
        
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
    
]

DJANGO_ADMIN_FORCE_ALLAUTH=True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.CookieJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # "DE
    # FAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=180),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access_token',  # আপনি যে নামে কুকি সেভ করেছেন
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
    'AUTH_COOKIE_SECURE': True,      # ← এটা না থাকলে ডিফল্ট True → cookie ব্লক
    'AUTH_COOKIE_PATH': '/',
}
JWT_AUTH_SECURE = False

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js dev
    "http://127.0.0.1:3000",
    "http://localhost:3001",  # Next.js dev
    "http://127.0.0.1:3001",
]

CSRF_COOKIE_DOMAIN = '.newsmartagent.com'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_DOMAIN = '.newsmartagent.com'
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
# EMAIL_BACKEND = 'django_mailjet.backends.MailjetBackend'

# MAILJET_API_KEY = 'd7fa03c2b6d8be8314e85dfce82f2cb7'
# MAILJET_SECRET_KEY = '3d9fdd7b0ff557a559a915f7d5b393ee'

SECURE_SSL_REDIRECT = False

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587

EMAIL_HOST_USER = "newsmartagentbd@gmail.com"
EMAIL_HOST_PASSWORD = "wbzh nmlh ndtt lxja"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



ACCOUNT_LOGIN_METHODS = {"email"}
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
# https://docs.allauth.org/en/latest/account/configuration.html
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# FORM_RENDERER = "django.forms.renderers.TemplatesSetting"
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_REQUIRED = True


# sslcomerz

SSLCOMMERZ_STORE_ID = "newsm6980a0f911f3f"
SSLCOMMERZ_STORE_PASSWORD = 'newsm6980a0f911f3f@ssl'
SSLCOMMERZ_SANDBOX = True
SITE_URL = "http://localhost:3000"



GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
GROK_API_KEY = os.environ.get('GROK_API_KEY')

FB_APP_ID = os.environ.get('FB_APP_ID')
FB_APP_SECRET = os.environ.get('FB_APP_SECRET')
FB_REDIRECT_URI = os.environ.get('FB_REDIRECT_URI')



CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("REDIS_URL", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ─── Google Drive Log Sync Config ────────────────────────────────────────────
# .env ফাইলে এই variable গুলো set করুন:
# GOOGLE_DRIVE_LOG_FOLDER_ID=<আপনার Google Drive folder id>
# GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE=<path to service_account.json>
GOOGLE_DRIVE_LOG_FOLDER_ID = os.environ.get('GOOGLE_DRIVE_LOG_FOLDER_ID', '')
GOOGLE_DRIVE_LOG_SUBFOLDER = os.environ.get('GOOGLE_DRIVE_LOG_SUBFOLDER', 'newsmartagent-logs')
GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE = os.environ.get(
    'GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE',
    '/app/service_account.json'  # BASE_DIR সরিয়ে সরাসরি এই পাথটি দিন
)

BAILEYS_API_URL = os.getenv('BAILEYS_API_URL', 'http://newsmartagent-baileys:3001')
BAILEYS_API_SECRET = os.getenv('BAILEYS_API_SECRET', 'nsa-baileys-secret-2024')
# ─────────────────────────────────────────────────────────────────────────────

# Celery Beat: প্রতি ৫ মিনিটে Drive sync
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'sync-logs-to-google-drive': {
        'task': 'log_service.sync_logs_to_drive',
        'schedule': crontab(minute='*/5'),  # প্রতি ৫ মিনিটে
    },
    'backup-database-to-google-drive': {
        'task': 'log_service.backup_db_to_drive',
        'schedule': crontab(hour=1, minute=0),  # প্রতিদিন রাত ১টায়
    },
    'backup-redis-to-google-drive': {
        'task': 'log_service.backup_redis_to_drive',
        'schedule': crontab(hour=2, minute=0),  # প্রতিদিন রাত ২টায়
    },
}


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} | {levelname} | {name} | {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        # Django + AI Agent log → ai_agent.log
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "ai_agent.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        # Celery log → আলাদা celery_worker.log
        "celery_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "celery_worker.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "celery": {
            "handlers": ["console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
        "aiAgent": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "log_service": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}




from django.utils.translation import gettext_lazy as _

UNFOLD = {
    # সাইটের টাইটেল ও হেডার
    "SITE_TITLE": "New Smart Agent Admin",
    "SITE_HEADER": "New Smart Agent",
    "SITE_SYMBOL": "smart_toy",  # Material icon: smart_toy

    # সাইডবারের history & view on site
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,

    # কালার প্যালেট: primary color + dark mode ready
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "147 51 234",
            "600": "126 34 206",
            "700": "107 33 168",
            "800": "88 28 135",
            "900": "76 29 149",
            "950": "46 16 101",
        },
    },

    # সাইডবার কাস্টমাইজেশন
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Main Navigation"),
                "separator": True,
                "items": [
                    {"title": _("Dashboard"), "icon": "dashboard", "link": "/admin/"},
                    {"title": _("Users & Permissions"), "icon": "group", "link": "/admin/users/user/"},
                ],
            },
            {
                "title": _("AI & Automation"),
                "separator": True,
                "items": [
                    {"title": _("AI Agents"), "icon": "psychology", "link": "/admin/aiAgent/aiagent/"},
                    {"title": _("Workflows (n8n)"), "icon": "account_tree", "link": "https://dev-n8n.newsmartagent.com", "external": True},
                ],
            },
        ],
    },

    # কোনো custom component ব্যবহার করবো না
    "COMPONENTS": {},
}