worker_processes auto;
events {
    worker_connections 2048; # একসাথে অনেক রিকোয়েস্ট হ্যান্ডেল করার জন্য বাড়ানো হলো
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 🛑 রেট লিমিটিং জোন তৈরি (DDoS ডিফেন্স)
    # প্রতি আইপি থেকে সেকেন্ডে সর্বোচ্চ ১০টি রিকোয়েস্ট অ্যালাউ করবে
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    # পারফরম্যান্স বুস্টারস
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off; # এনজিনেক্স এর ভার্সন হাইড করার জন্য (Security)

    # জিপ কম্প্রেশন (অপ্টিমাইজড)
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;
    # এই লাইনটি আপনার সাব-কনফিগগুলোকে এখানে টেনে আনবে 👇
    include /etc/nginx/conf.d/*.conf;

}