from django.contrib import admin
from .models import DocumentKnowledge

@admin.register(DocumentKnowledge)
class DocumentKnowledgeAdmin(admin.ModelAdmin):
    # প্যানেলের লিস্ট ভিউতে যা যা দেখাবে
    list_display = ('user', 'doc_title', 'chunk_index', 'created_at', 'get_embedding_preview')
    
    # ফিল্টার করার অপশন
    list_filter = ('user', 'created_at', 'doc_title')
    
    # সার্চ করার অপশন
    search_fields = ('doc_title', 'content', 'user__email')
    
    # শুধুমাত্র পড়ার জন্য (Embedding সাধারণত এডিট করার প্রয়োজন হয় না)
    readonly_fields = ('created_at', 'embedding_full_view')

    def get_embedding_preview(self, obj):
        """ভেক্টরের প্রথম কয়েকটা ভ্যালু প্রিভিউ হিসেবে দেখাবে"""
        if obj.embedding:
            # প্রথম ৫টি ভ্যালু লিস্ট হিসেবে দেখাবে
            return f"{list(obj.embedding)[:5]}..."
        return "No Vector"
    get_embedding_preview.short_description = "Embedding Preview"

    def embedding_full_view(self, obj):
        """ডিটেইল ভিউতে পুরো ভেক্টর ডাটা দেখাবে"""
        return list(obj.embedding) if obj.embedding else "No Vector"
    embedding_full_view.short_description = "Full Vector Data"

    # ডিটেইল পেজে ফিল্ডগুলোর সাজানো ব্যবস্থা
    fieldsets = (
        ('Basic Information', {
            'fields': ('user', 'doc_title', 'chunk_index')
        }),
        ('Content', {
            'fields': ('content',)
        }),
        ('Vector Data', {
            'fields': ('embedding_full_view', 'created_at'),
            'description': 'Vector embedding generated by AI model (e.g., Gemini).'
        }),
    )