from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from aiAgent.models import AgentAI, WidgetSettings
from aiAgent.serializers import WidgetSettingsSerializer
from aiAgent.business_logic.logic_handler import handle_ai_response
import logging

logger = logging.getLogger(__name__)

class WidgetConfigView(APIView):
    """
    Publicly accessible endpoint to fetch widget configuration using widget_key.
    """
    authentication_classes = []
    permission_classes = []

    def get(self, request, widget_key):
        agent = get_object_or_404(AgentAI, widget_key=widget_key, platform='web_widget', is_active=True)
        settings = agent.get_settings # This is AgentAISettings, not WidgetSettings
        
        # Get WidgetSettings
        widget_settings, _ = WidgetSettings.objects.get_or_create(agent=agent)
        
        return Response({
            "name": agent.name,
            "greeting": agent.greeting_message or "Hello! How can I help you?",
            "settings": WidgetSettingsSerializer(widget_settings).data
        })

class WidgetChatView(APIView):
    """
    Publicly accessible endpoint for the widget to send messages.
    """
    authentication_classes = []
    permission_classes = []

    def post(self, request, widget_key):
        agent = get_object_or_404(AgentAI, widget_key=widget_key, platform='web_widget', is_active=True)
        message = request.data.get('message')
        sender_uuid = request.data.get('sender_id') # A unique ID generated by the widget for this visitor

        if not message or not sender_uuid:
            return Response({"error": "Message and sender_id are required"}, status=status.HTTP_400_BAD_REQUEST)

        try:
            # Handle AI response using existing logic
            # sender_id is used for memory persistence
            response_text = handle_ai_response(
                agent_id=agent.id,
                sender_id=sender_uuid,
                message_text=message,
                platform='web_widget'
            )
            
            return Response({"response": response_text})
        except Exception as e:
            logger.error(f"Error in WidgetChatView: {e}", exc_info=True)
            return Response({"error": "Failed to process message"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
