from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404
from aiAgent.models import AgentAI, WidgetSettings
from aiAgent.serializers import WidgetSettingsSerializer
from webhooks.tasks import process_ai_reply_task
import logging
import uuid
import os

logger = logging.getLogger(__name__)

DEFAULT_BUBBLE_ICON_URL = '/newsmartagent_ai_logo.jpeg'


class WidgetConfigView(APIView):
    """
    Publicly accessible endpoint to fetch widget configuration using widget_key.
    """
    authentication_classes = []
    permission_classes = []

    def get(self, request, widget_key):
        agent = get_object_or_404(AgentAI, widget_key=widget_key, platform='web_widget', is_active=True)
        
        # Get or create WidgetSettings
        widget_settings, _ = WidgetSettings.objects.get_or_create(agent=agent)
        
        settings_data = WidgetSettingsSerializer(widget_settings).data
        
        # Build absolute URLs for external consumption (the widget script)
        request_host = request.get_host()
        protocol = 'https' if request.is_secure() or request.headers.get('X-Forwarded-Proto') == 'https' else 'http'
        base_url = f"{protocol}://{request_host}"

        raw_icon_url = widget_settings.bubble_icon_url or DEFAULT_BUBBLE_ICON_URL
        if raw_icon_url.startswith('/'):
            effective_icon_url = f"{base_url}{raw_icon_url}"
        else:
            effective_icon_url = raw_icon_url

        settings_data['effective_icon_url'] = effective_icon_url
        
        # New fields for frontend widget script
        settings_data['bubble_roundness'] = widget_settings.bubble_roundness
        settings_data['show_bubble_background'] = widget_settings.show_bubble_background

        response = Response({
            "name": agent.name,
            "greeting": agent.greeting_message or "Hello! How can I help you?",
            "settings": settings_data
        })
        response['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
        return response


class WidgetChatView(APIView):
    """
    Publicly accessible endpoint for the widget to send messages.
    """
    authentication_classes = []
    permission_classes = []

    def post(self, request, widget_key):
        agent = get_object_or_404(AgentAI, widget_key=widget_key, platform='web_widget', is_active=True)
        message = request.data.get('message')
        sender_uuid = request.data.get('sender_id')  # A unique ID generated by the widget for this visitor

        if not message or not sender_uuid:
            return Response({"error": "Message and sender_id are required"}, status=status.HTTP_400_BAD_REQUEST)

        try:
            import time
            import uuid
            
            data = {
                'widget_key': str(widget_key),
                'page_id': f"widget_{widget_key}",
                'sender_id': sender_uuid,
                'message': message,
                'type': 'web_widget',
                'message_id': str(uuid.uuid4()),
                'timestamp': int(time.time() * 1000)
            }
            
            # Call the unified pipeline synchronously
            response_text = process_ai_reply_task(data)
            
            if not response_text:
                response_text = "I'm sorry, I am unable to reply at the moment. Please try again later."
                
            return Response({"response": response_text})
        except Exception as e:
            logger.error(f"Error in WidgetChatView: {e}", exc_info=True)
            return Response({"error": "Failed to process message"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class WidgetIconUploadView(APIView):
    """
    Authenticated endpoint to upload a custom bubble icon for the widget.
    Saves the file to MinIO/media storage and updates bubble_icon_url in WidgetSettings.
    """
    permission_classes = [IsAuthenticated]

    def post(self, request, agent_id):
        agent = get_object_or_404(AgentAI, id=agent_id, user=request.user, platform='web_widget')
        icon_file = request.FILES.get('icon')

        if not icon_file:
            return Response({"error": "No icon file provided."}, status=status.HTTP_400_BAD_REQUEST)

        # Validate file type
        allowed_types = ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml']
        if icon_file.content_type not in allowed_types:
            return Response({"error": "Invalid file type. Allowed: JPEG, PNG, GIF, WEBP, SVG."}, status=status.HTTP_400_BAD_REQUEST)

        # Generate unique filename
        ext = os.path.splitext(icon_file.name)[1].lower() or '.png'
        filename = f"widget_icons/{request.user.id}/{agent.id}_{uuid.uuid4().hex[:8]}{ext}"

        try:
            from django.core.files.storage import default_storage
            from django.conf import settings as django_settings

            # Auto-create the bucket if missing (MinIO/S3)
            try:
                import boto3
                bucket_name = getattr(django_settings, 'AWS_STORAGE_BUCKET_NAME', None)
                endpoint_url = getattr(django_settings, 'AWS_S3_ENDPOINT_URL', None)
                if bucket_name and endpoint_url:
                    s3 = boto3.client(
                        's3',
                        endpoint_url=endpoint_url,
                        aws_access_key_id=getattr(django_settings, 'AWS_ACCESS_KEY_ID', ''),
                        aws_secret_access_key=getattr(django_settings, 'AWS_SECRET_ACCESS_KEY', ''),
                    )
                    try:
                        s3.head_bucket(Bucket=bucket_name)
                    except Exception:
                        s3.create_bucket(Bucket=bucket_name)
                        logger.info(f"Created MinIO bucket: {bucket_name}")
            except Exception as bucket_err:
                logger.warning(f"Could not auto-create bucket: {bucket_err}")

            # Save file to storage backend (MinIO in production)
            saved_path = default_storage.save(filename, icon_file)
            icon_url = default_storage.url(saved_path)

            # Update WidgetSettings
            widget_settings, _ = WidgetSettings.objects.get_or_create(agent=agent)
            widget_settings.bubble_icon_url = icon_url
            widget_settings.bubble_icon = 'image'
            widget_settings.save()

            return Response({"icon_url": icon_url})
        except Exception as e:
            logger.error(f"Error uploading widget icon: {e}", exc_info=True)
            return Response({"error": "Failed to upload icon."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class WidgetStatusView(APIView):
    """
    Publicly accessible endpoint to get the current human/AI state for a sender.
    Widget polls this on load to sync button states with server.
    """
    authentication_classes = []
    permission_classes = []

    def get(self, request, widget_key):
        from aiAgent.models import Contact
        agent = get_object_or_404(AgentAI, widget_key=widget_key, platform='web_widget', is_active=True)
        sender_id = request.query_params.get('sender_id')
        if not sender_id:
            return Response({"is_human_active": False, "is_ai_active": True})

        contact = Contact.objects.filter(agent=agent, identifier=sender_id).first()
        if not contact:
            return Response({"is_human_active": False, "is_ai_active": True})

        return Response({
            "is_human_active": contact.is_human_needed,
            "is_ai_active": contact.is_auto_reply_enabled,
        })


class WidgetControlView(APIView):
    """
    Publicly accessible endpoint for the widget to toggle human/AI mode.
    """
    authentication_classes = []
    permission_classes = []

    def post(self, request, widget_key):
        from aiAgent.models import Contact
        agent = get_object_or_404(AgentAI, widget_key=widget_key, platform='web_widget', is_active=True)
        sender_id = request.data.get('sender_id')
        action = request.data.get('action')  # 'human_request', 'human_resolved', 'stop_ai', 'start_ai'

        if not sender_id or not action:
            return Response({"error": "sender_id and action are required"}, status=status.HTTP_400_BAD_REQUEST)

        contact, _ = Contact.objects.get_or_create(
            agent=agent,
            identifier=sender_id,
            defaults={'platform': 'web_widget'}
        )

        if action == 'human_request':
            contact.is_human_needed = True
            contact.is_auto_reply_enabled = False
            contact.save()
            return Response({"status": "ok", "is_human_active": True, "is_ai_active": False})

        elif action == 'human_resolved':
            contact.is_human_needed = False
            contact.is_auto_reply_enabled = True
            contact.save()
            return Response({"status": "ok", "is_human_active": False, "is_ai_active": True})

        elif action == 'stop_ai':
            contact.is_auto_reply_enabled = False
            contact.save()
            return Response({"status": "ok", "is_ai_active": False})

        elif action == 'start_ai':
            contact.is_auto_reply_enabled = True
            contact.save()
            return Response({"status": "ok", "is_ai_active": True})

        return Response({"error": "Invalid action"}, status=status.HTTP_400_BAD_REQUEST)
