# Generated by Django 6.0.1 on 2026-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_agent', '0002_alter_referralrelation_referred_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managentconfig',
            name='otp_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
