
###
GET http://dev.newsmartagent.com/api/AgentAI/available-models/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczMjQ2MTUyLCJpYXQiOjE3NzMyNDI1NTIsImp0aSI6ImI0NTg0ZjJiOTc4NDQzZDZhZmY4MmIwODI1OWEyMDZkIiwidXNlcl9pZCI6IjIifQ.6zjLAeaoyZHSXGjyfkGr0Uijr3Ut1N95CXpKRUbSKPc

{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}



###
GET http://dev.newsmartagent.com/api/offers/7/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczMDU4NjA1LCJpYXQiOjE3NzMwNTUwMDUsImp0aSI6ImRmZWM5NGRlOWY4MTRjNWJiYTdlNmM3NmNkYzBhYWViIiwidXNlcl9pZCI6IjIifQ.6_onmhZWlnf--cJpbSBgS_kgFJ2YK2jVStzx-DJOVhA




{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}


###
GET https://newsmartagent.com/api/users/me/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTA5MzU3LCJpYXQiOjE3NzM5MDU3NTcsImp0aSI6ImJkZWNjN2E5MDQ4YjQ2MDRhNTVjNjYwZDA2N2I3NTdlIiwidXNlcl9pZCI6IjIifQ.ODzJnMIhXedMl_vzSCFki3aeEsg_moKrRn0JIrUiEwE


{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}


###
GET https://newsmartagent.com/api/AgentAI/ranking/947204378476536/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMTk0MjA3LCJpYXQiOjE3NzIxOTA2MDcsImp0aSI6IjhiMzE1NzUwYTk2ODRjMDY5MGU4ZDY1YzkwMjExMDc2IiwidXNlcl9pZCI6IjIifQ.cBfsOrNMrtWNjAsvcpBspMrBk2MKASXGo_NogUb_yIE


{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}


###
GET https://newsmartagent.com/api/embedding/documents/3
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczNDQ2MzU2LCJpYXQiOjE3NzM0NDI3NTYsImp0aSI6ImM4ZTI1OGQ3OWI5NTQxNzVhZDdiYWVmNjkzMjJkZjY1IiwidXNlcl9pZCI6IjIifQ.Z-t5awXkRQbtU-ZgM3l3L-KOLuyVmnwLUmBXTH61G3k


{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}


###
GET https://newsmartagent.com/api/AgentAI/schedule/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NzIxNTU0LCJpYXQiOjE3NzQ3MTc5NTQsImp0aSI6IjQ1Mjc4YjcwMzgwNjRiNmJhNTliYjRkODgyMjg2YzIyIiwidXNlcl9pZCI6IjIifQ.Xv6W3vEcZJERKfEZmt2w8702yc-bFftFRy0NswmgHms

{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}


curl -X POST http://localhost:8000/api/AgentAI/schedule/ \
  -H "Content-Type: application/json" \
  -H "Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NzIxNTU0LCJpYXQiOjE3NzQ3MTc5NTQsImp0aSI6IjQ1Mjc4YjcwMzgwNjRiNmJhNTliYjRkODgyMjg2YzIyIiwidXNlcl9pZCI6IjIifQ.Xv6W3vEcZJERKfEZmt2w8702yc-bFftFRy0NswmgHms" \
  -d '{
    "agent_id": "24",
    "message": "Hello from Container!",
    "run_at": "2026-03-29T10:00:00+06:00",
    "filters": {
      "lead_stage": "all",
      "start_date": null,
      "end_date": null
    }
  }'