
###
GET http://localhost/api/offers/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMjIzMTEyLCJpYXQiOjE3NzEyMTk1MTIsImp0aSI6IjRkNWI3YjdhZDBlMDRkNTg4YmNkYzFhMDFmNWRiMWFiIiwidXNlcl9pZCI6IjQ2In0.GnFPcrefuuPdaLebYRRyo9WBE--YRKqxhly7lyLdEv4


{
    'email': 'newpart444@gmail.com',
    'password': '1234'
}


###
GET http://localhost/api/users/me/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzI2MzQwLCJpYXQiOjE3NzEzMjI3NDAsImp0aSI6ImYwZDExNzQ2MjI5NjQzNjM4YzRhOTY3MThkNzZlYzFhIiwidXNlcl9pZCI6IjIifQ.myAQpOpYOI7SviLOTHyXl86yRLpiPeCD3Td9iabLUX0


{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}


###
GET http://localhost/api/notifications/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzI2MzQwLCJpYXQiOjE3NzEzMjI3NDAsImp0aSI6ImYwZDExNzQ2MjI5NjQzNjM4YzRhOTY3MThkNzZlYzFhIiwidXNlcl9pZCI6IjIifQ.myAQpOpYOI7SviLOTHyXl86yRLpiPeCD3Td9iabLUX0


{
    'email': 'junayed75489@gmail.com',
    'password': '1234'
}


