
###
GET http://localhost/api/offers/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMjIzMTEyLCJpYXQiOjE3NzEyMTk1MTIsImp0aSI6IjRkNWI3YjdhZDBlMDRkNTg4YmNkYzFhMDFmNWRiMWFiIiwidXNlcl9pZCI6IjQ2In0.GnFPcrefuuPdaLebYRRyo9WBE--YRKqxhly7lyLdEv4


{
    'email': 'newpart444@gmail.com',
    'password': '1234'
}


###
GET http://localhost/api/users/me/
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMjY3Mzg5LCJpYXQiOjE3NzEyNjM3ODksImp0aSI6Ijk2NjQ1ZDliMzE1MDRiYTliOTU2MDNiNjVjZDA5ZWZiIiwidXNlcl9pZCI6IjIifQ.DmxJ-AoZDBFGoCDRe699yuo4EhuLm25QfngGeJi6WWs


{
    'email': 'newpart444@gmail.com',
    'password': '1234'
}