name: Docker Deploy to Oracle VPS

# যখনই মেইন ব্রাঞ্চে পুশ করবেন, তখনই এই অ্যাকশনটি শুরু হবে
on:
  push:
    branches: [ main ]  # আপনার মেইন ব্রাঞ্চের নাম যদি 'master' হয়, তবে এখানে master লিখবেন

jobs:
  deploy:
    runs-on: self-hosted  # এটিই আপনার ভিপিএস-এর রানারকে কল করবে

    steps:
      - name: Fix Permissions
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          # যদি আগে থেকে কোনো কন্টেইনার চলে, তবে তা বন্ধ করবে
          cp ~/newsmartagent.env .env
          
          
          # নতুন করে ইমেজ বিল্ড করবে এবং ব্যাকগ্রাউন্ডে রান করবে
          docker-compose up -d --build --remove-orphans
          
          # অপ্রয়োজনীয় পুরনো ইমেজগুলো ডিলিট করে মেমরি বাঁচাবে
          docker image prune -f